[tool.poetry]
name = "robocorp-devutils"
version = "0.0.1"
description = "Utilities for development in monorepo."
authors = [
	"Fabio Z. <fabio@robocorp.com>",
	"Kerkko P. <kerkko@robocorp.com>",
	"Ossi R. <ossi@robocorp.com>",
	"Antero V. <antero@robocorp.com>",
]
readme = "README.md"
packages = [{include = "devutils", from="src"}]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.group.dev.dependencies]
black = "^23.1.0"
ruff = "^0.0.255"
mypy = "^1.1.1"
pytest = "^7.2.2"
pytest-xdist = "^3.2.1"
pytest-regressions = "1.0.6"
pydocstyle = "^6.3.0"
isort = "^5.12.0"
types-invoke = "^2.0"
invoke = "^2.0"
lazydocs = { git = "https://github.com/robocorp/lazydocs.git" }

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
