name: 🐛 Bug report
description: Submit a bug report to help us make Sema4.ai Actions better
labels: [ Bug ]
body:
  - type: textarea
    attributes:
      label: What is wrong
      description: >-
        Give details on what you are doing, what you expect to happen, and what
        is currently happening.
      placeholder: |
        * I'm trying to use the `Sema4.ai` library to do X
        * I expected to get Y
        * Instead it does Z
    validations:
      required: true
  - type: textarea
    attributes:
      label: System info
      description: Sharing your system information will help us with debugging.
      placeholder: |
        * Target component / library version
        * Python version
        * OS version (Windows: ´ver´ / macOS: `sw_vers` / linux: `uname -r` )
    validations:
      required: true
  - type: textarea
    attributes:
      label: Example script
      description: >-
        If possible, please provide an automation example which replicates the problem.
        Including any input/output data sample to test the example with.
        (⚠️do not share sensitive information as this is a public source)
      placeholder: |
        * Here's the isolated script block which highlights the bug
        * Which is operating on this file
        * And produces this behaviour/output instead of the expected one
