name: CLI Tests

on:
  push:
    branches:
      - "master"
      - "wip"
    paths:
      - "cli/**"
      - "tasks/**"
      - "log/**"
      - ".github/workflows/cli_tests.yml"
  pull_request:
    branches:
      - "master"
    paths:
      - "cli/**"
      - ".github/workflows/cli_tests.yml"

defaults:
  run:
    working-directory: ./cli

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          cache-dependency-path: cli/go.sum
      - name: Install invoke
        run: pipx install invoke
      - name: Prepare
        run: invoke prepare
      - name: Lint
        run: invoke lint
      - name: Test
        run: invoke test
