name: Logging Release

on:
  push:
#     branches:
#       - "release-robocorp-log"
    tags:
      - "robocorp-log-*"

defaults:
  run:
    working-directory: './log'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: true

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v3

    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: 16.x

    - name: Install poetry
      run: pipx install poetry
      
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
        cache: 'poetry'

    - name: Install project
      run: poetry install

    - name: Embed output view in index.py
      run: poetry run python -m dev build-output-view
        
    - name: Check tag version
      run: poetry run python -m dev check-tag-version
      
    - name: Build with poetry
      run: poetry build
      
    - name: Upload to PyPI
      run: |
        poetry config pypi-token.pypi  ${{ secrets.PYPI_TOKEN_ROBOCORP_ROBOLOG }}
        poetry publish
